/** Shared tuning for the same virtual world on both laptops. */
export const CONFIG={
 INPUT_HZ:60,STATE_BROADCAST_HZ:60,PHYSICS_HZ:120,
 TABLE_Y:.95,HALF_WIDTH:1.65,HALF_LENGTH:2.65,NET_HEIGHT:.23,HIT_PLANE_Z:2.83,
 BASE_RETURN_SPEED:5.1,MAX_RETURN_SPEED:7.8,RALLY_SPEED_GAIN:.025,SWING_SPEED_GAIN:.4,LANDING_Z:1.42,LANDING_X:1.35,PADDLE_SMOOTHING:32,MAX_STEP:.05,SUBSTEP_DISTANCE:.025,TARGET_RADIUS:.57,TARGET_INITIAL_DELAY:5,TARGET_INTERVAL:8,MAX_TARGETS:2,SERVE_DELAY:1.05,INITIAL_SERVE_DELAY:1.2,INPUT_TIMEOUT_MS:1600,STARTUP_INPUT_TIMEOUT_MS:6000,SEAT_RECOVERY_MS:60000,FORM_TIMEOUT:5,
 MIN_LIFT:1.4,MAX_VERTICAL_SPEED:8,MAX_LATERAL_SPEED:3.2,MAX_BALL_SPEED:13,NET_CLEARANCE:.12,
 BALL_RADIUS:.065,GRAVITY:6.8,RESTITUTION:.86,PADDLE_RADIUS_X:.48,PADDLE_RADIUS_Y:.58,
 PADDLE_X_RANGE:1.72,PADDLE_MIN_Y:1.03,PADDLE_MAX_Y:2.7,PADDLE_CENTER_Y:1.5,
 BIG_RACKET_MULTIPLIER:1.6,BIG_RACKET_DURATION:8,SMASH_MULTIPLIER:1.4,
 MATCH_TARGET_SCORE:7,FORM_BEFORE_MS:250,FORM_AFTER_MS:160,
 PERFECT_THRESHOLD:90,GREAT_THRESHOLD:75,OK_THRESHOLD:55,
 POWER_PER_PERFECT:25,POWER_PER_GREAT:15,POWER_PER_OK:5,
 CV_HZ:45,NETWORK_INTERPOLATION_MS:60,NETWORK_EXTRAPOLATION_MS:100,TRACKING_INIT_TIMEOUT_MS:15000,MIRROR_INPUT:true,SHOULDERS_STABLE_MS:500,HAND_SELECT_MS:500,CENTER_HOLD_MS:1000,
 POSE_HISTORY_MS:700,TRACKING_LOSS_MS:900,
} as const;

export const POSE_CONFIG={bodyMs:CONFIG.SHOULDERS_STABLE_MS,handMs:CONFIG.HAND_SELECT_MS,neutralMs:CONFIG.CENTER_HOLD_MS,historyMs:CONFIG.POSE_HISTORY_MS,visibility:.5,mirror:CONFIG.MIRROR_INPUT} as const;
export const FORM_CONFIG={beforeMs:250,afterMs:160,speedTarget:3,timingMinSpeed:.6,followDistance:.2,perfect:90,great:75,ok:55} as const;
